name: LuaRocks release
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - "*"
  pull_request: # Will test a local install without uploading to luarocks.org

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            plenary.nvim
          labels: |
            neovim
            minuet-ai.nvim
          detailed_description: |
            - AI-powered code completion with dual modes:
              - Specialized prompts and various enhancements for chat-based LLMs on code completion tasks.
              - Fill-in-the-middle (FIM) completion for compatible models (DeepSeek,
                Codestral, Qwen, and others).
            - Support for multiple AI providers (OpenAI, Claude, Gemini, Codestral, Ollama, and
              OpenAI-compatible services)
            - Customizable configuration options
            - Streaming support to enable completion delivery even with slower LLMs
            - Support `nvim-cmp`, `blink-cmp`, `virtual text` frontend
